"""add_categoria_tipo_restriccion_to_tipo_ausencia

Revision ID: 12a7fbf5ea82
Revises: c0eab6ae6b18
Create Date: 2026-04-27 17:51:29.940187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a7fbf5ea82'
down_revision = 'c0eab6ae6b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual add: Create ENUM type for postgres
    categoria_enum = sa.Enum('AUSENCIA', 'RESTRICCION', name='categoriaausencia')
    categoria_enum.create(op.get_bind())

    with op.batch_alter_table('tipo_ausencia', schema=None) as batch_op:
        # Primero agregar como nullable para evitar error con filas existentes
        batch_op.add_column(sa.Column('categoria', sa.Enum('AUSENCIA', 'RESTRICCION', name='categoriaausencia'), nullable=True))
        batch_op.add_column(sa.Column('tipo_restriccion', sa.String(length=30), nullable=True))

    # Actualizar filas existentes
    op.execute("UPDATE tipo_ausencia SET categoria = 'AUSENCIA' WHERE categoria IS NULL")

    # Ahora poner NOT NULL
    with op.batch_alter_table('tipo_ausencia', schema=None) as batch_op:
        batch_op.alter_column('categoria', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_ausencia', schema=None) as batch_op:
        batch_op.drop_column('tipo_restriccion')
        batch_op.drop_column('categoria')

    # Manual add: Drop ENUM type for postgres
    sa.Enum(name='categoriaausencia').drop(op.get_bind())
    # ### end Alembic commands ###
