"""eliminar_trabajador_preferencia

Revision ID: 24d78431b0e4
Revises: aaab6f30d160
Create Date: 2026-04-29 12:36:58.416664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d78431b0e4'
down_revision = 'aaab6f30d160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trabajador_preferencia')
    with op.batch_alter_table('tipo_ausencia_plantilla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.Enum('AUSENCIA', 'RESTRICCION', name='categoriaausencia'), nullable=False))
        batch_op.add_column(sa.Column('tipo_restriccion', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_ausencia_plantilla', schema=None) as batch_op:
        batch_op.drop_column('tipo_restriccion')
        batch_op.drop_column('categoria')

    op.create_table('trabajador_preferencia',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trabajador_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dia_semana', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('turno', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), server_default=sa.text("'preferencia'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajador.id'], name=op.f('trabajador_preferencia_trabajador_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('trabajador_preferencia_pkey'))
    )
    # ### end Alembic commands ###
