"""add_parametro_legal_and_restriccion_turno

Revision ID: 69f36977a995
Revises: c3d4e5f6a7b8
Create Date: 2026-04-27 16:41:36.389814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f36977a995'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual Enum creation
    tipocontrato = sa.Enum('FULL_TIME', 'PART_TIME_30', 'PART_TIME_20', name='tipocontrato')
    tipocontrato.create(op.get_bind())

    op.create_table('parametro_legal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('es_obligatorio', sa.Boolean(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('trabajador_restriccion_turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('naturaleza', sa.String(length=10), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('dias_semana', sa.JSON(), nullable=True),
    sa.Column('turno_id', sa.Integer(), nullable=True),
    sa.Column('turno_alternativo_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajador.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turno_alternativo_id'], ['turno.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['turno_id'], ['turno.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # with op.batch_alter_table('trabajador', schema=None) as batch_op:
    #     batch_op.alter_column('tipo_contrato',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.Enum('FULL_TIME', 'PART_TIME_30', 'PART_TIME_20', name='tipocontrato'),
    #            existing_nullable=False)
    
    # Postgres specific cast with value mapping
    op.execute("""
        ALTER TABLE trabajador ALTER COLUMN tipo_contrato TYPE tipocontrato 
        USING (
            CASE 
                WHEN tipo_contrato = 'full-time' THEN 'FULL_TIME'
                WHEN tipo_contrato = 'part-time' THEN 'PART_TIME_30'
                ELSE 'FULL_TIME'
            END
        )::tipocontrato
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajador', schema=None) as batch_op:
        batch_op.alter_column('tipo_contrato',
               existing_type=sa.Enum('FULL_TIME', 'PART_TIME_30', 'PART_TIME_20', name='tipocontrato'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    op.drop_table('trabajador_restriccion_turno')
    op.drop_table('parametro_legal')
    # Manual Enum drop
    sa.Enum('FULL_TIME', 'PART_TIME_30', 'PART_TIME_20', name='tipocontrato').drop(op.get_bind())
    # ### end Alembic commands ###
