"""add es_base to menu

Revision ID: aaab6f30d160
Revises: 3af2f66b6e19
Create Date: 2026-04-28 11:25:46.979983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaab6f30d160'
down_revision = '3af2f66b6e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_base', sa.Boolean(), server_default='false', nullable=False))

    with op.batch_alter_table('usuario_empresa', schema=None) as batch_op:
        batch_op.alter_column('activo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.drop_index(batch_op.f('ix_ue_empresa'))
        batch_op.drop_index(batch_op.f('ix_ue_usuario'))
        batch_op.drop_constraint(batch_op.f('uq_usuario_empresa'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_empresa', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_usuario_empresa'), ['usuario_id', 'empresa_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_ue_usuario'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ue_empresa'), ['empresa_id'], unique=False)
        batch_op.alter_column('activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('es_base')

    # ### end Alembic commands ###
