"""add_categoria_to_parametro_legal

Revision ID: c0eab6ae6b18
Revises: 69f36977a995
Create Date: 2026-04-27 17:22:43.591172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0eab6ae6b18'
down_revision = '69f36977a995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parametro_legal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=50), nullable=False, server_default='General'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parametro_legal', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
