"""add restriccion_id to trabajador_ausencia

Revision ID: c18184e4a3f7
Revises: 12a7fbf5ea82
Create Date: 2026-04-27 18:09:48.495506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c18184e4a3f7'
down_revision = '12a7fbf5ea82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajador_ausencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restriccion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'trabajador_restriccion_turno', ['restriccion_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajador_ausencia', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('restriccion_id')

    # ### end Alembic commands ###
